### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by hoblin** [hoblin/x-tracker#14]
- [x] Add user_id to the TweetMetrics and Tweets and set all records to the first user
- [x] Add unique hash to Tweet to use in tracker requests 
  - add DB index on it
  - this way, only the user who added the tweet can track it. That's how to prevent data manipulation in the early stage of development. Later, adding a separate model and generating unique hashes for other users who would like to track the same tweet makes sense.
- [x] Add API endpoint to receive metrics
  - accept stats
  - accept optional tweet details
  - respond with the command to gather tweet details if these are not stored yet
- [x] Convert script to the template.
  - add /tweets/:id/track action which will respond with Tampermonkey script
  - Set the script name as a "tweet.author#tweet.id"
  - Set the tweet URL
  - Set the Tweet UUID
- [x] Add new/create actions for tweets
  - accept only the tweet URL
  - At the top of the "new" template create instruction how to install the Tampermonkey, how to add tracker script and how to track tweet metrics in your browser.

- [x] Change tracker script to gather all stats

Gather the following values:
    - Likes
    - Views
    - Retweets
    - Quotes (need to add these)
    - Comments
    - Bookmarks

Related issues: 
-  #9
